[package]
name = "writer-demo"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
opentelemetry-stdout.workspace = true
